### PR TITLE
Remove this rehost IMMEDIATELY.

### PR DESCRIPTION
**Pull request by IMB11**
This content is extremely outdated, the majority of content has been moved to https://docs.fabricmc.net/

Please remove this rehost of the original website or I will seek less pleasant alternative methods for removal.

### CODE REVIEW

**Comment by IMB11** [comment]
@wellcoming 请立即移除此叉！

**Comment by wellcoming** [comment]
ok

**Comment by wellcoming** [comment]
But why? I just forked it for easy viewing.

**Comment by wellcoming** [comment]
Can I make the repository private for personal reference only? It won't be publicly accessible.

**Comment by IMB11** [comment]
Yes, but please dont make it public on a github pages site.

**Comment by IMB11** [comment]
Thank you :+1:

**Pull request closed without merging**
